#ifndef POSEIDON_DATA_H
#define POSEIDON_DATA_H

#include "tools.h"

#define AQUARIUM_WIDTH 1000
#define AQUARIUM_HEIGHT 1000
#define AQUARIUM_DIMENSIONS (struct dimension){AQUARIUM_WIDTH, AQUARIUM_HEIGHT}

#define SERVER_CMD_DELIMITER " "

#define SIGNAL_STOP_SENDING SIGUSR1
#define SIGNAL_NOTIFICATION SIGUSR2

int SPEED_RATE;

#endif //POSEIDON_DATA_H
